[package]
name = "vsas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
rusqlite = { version = "0.29.0", features = ["bundled-sqlcipher-vendored-openssl"] }
sha2 = "0.10.0"